export enum ORDER_STATUS {
  OPEN_ORDER = 1,
  CANCELLED,
  MATCHED,
  SELF_MATCHED,
}

export enum OrderStatus {
  'Open' = 1,
  'Canceled',
  'Completed',
  'SelfMatch',
  'Expired',
}

export enum OrderTypeEnum {
  'Limit',
  'IOC',
  'POST',
  'Market',
}

export enum OrderUpdateStaus {
  'created' = 1,
  'partially_filled',
  'removed',
}

export enum BLOCKCHAINS {
  "ALGORAND" = 'Algorand',
  // ARBITRUM = 'Arbitrum One',
  // ETHEREUM = 'Ethereum Goerli',
  // ETHEREUM_SEPOLIA = 'Ethereum Sepolia',
  // OPTIMISM = 'Optimism Testnet',
  // BASE = 'Base Testnet',
  // OPTIMISM_SEPOLIA = 'Optimism Sepolia',

  "SOLANA" = 'Solana',

  "5IRECHAIN_THUNDER_TESTNET"= "5ireChain Thunder Testnet",
  "ACALA"= "Acala",
  "ALFAJORES"= "Alfajores",
  "APOTHEM_NETWORK"= "Apothem Network",
  "ARBITRUM_GOERLI"= "Arbitrum Goerli",
  "ARBITRUM_NOVA"= "Arbitrum Nova",
  "ARBITRUM_ONE"= "Arbitrum",
  "ARBITRUM_SEPOLIA"= "Arbitrum Sepolia",
  "ASTAR"= "Astar",
  "ASTAR_ZKEVM_TESTNET_ZKATANA"= "Astar zkEVM Testnet zKatana",
  "AURORA"= "Aurora",
  "AURORA_TESTNET"= "Aurora Testnet",
  "AVALANCHE"= "Avalanche",
  "AVALANCHE_FUJI"= "Avalanche Fuji",
  "BAHAMUT"= "Bahamut",
  "BASE"= "Base",
  "BASE_GOERLI"= "Base Goerli",
  "BASE_SEPOLIA"= "Base Sepolia",
  "BEAR_NETWORK_CHAIN_MAINNET"= "Bear Network Chain Mainnet",
  "BEAR_NETWORK_CHAIN_TESTNET"= "Bear Network Chain Testnet",
  "BERACHAIN_ARTIO"= "Berachain Artio",
  "BERESHEET_BEREEVM_TESTNET"= "Beresheet BereEVM Testnet",
  "BINANCE_SMART_CHAIN_TESTNET"= "BNB Chain Testnet",
  "BITTORRENT"= "BitTorrent",
  "BITTORRENT_CHAIN_TESTNET"= "BitTorrent Chain Testnet",
  "BLACKFORT_EXCHANGE_NETWORK"= "BlackFort Exchange Network",
  "BLACKFORT_EXCHANGE_NETWORK_TESTNET"= "BlackFort Exchange Network Testnet",
  "BLAST_SEPOLIA"= "Blast Sepolia",
  "BNB_SMART_CHAIN"= "BNB Chain",
  "BOBA_NETWORK"= "Boba Network",
  "BRONOS"= "Bronos",
  "BRONOS_TESTNET"= "Bronos Testnet",
  "CANTO"= "Canto",
  "CELO"= "Celo",
  "CHILIZ_CHAIN"= "Chiliz Chain",
  "CHILIZ_SPICY_TESTNET"= "Chiliz Spicy Testnet",
  "CONFLUX_ESPACE"= "Conflux eSpace",
  "CONFLUX_ESPACE_TESTNET"= "Conflux eSpace Testnet",
  "CORE_DAO"= "Core Dao",
  "COSTON"= "Coston",
  "COSTON2"= "Coston2",
  "CRONOS_MAINNET"= "Cronos Mainnet",
  "CRONOS_TESTNET"= "Cronos Testnet",
  "CROSSBELL"= "Crossbell",
  "DEFICHAIN_EVM_MAINNET"= "DeFiChain EVM Mainnet",
  "DEFICHAIN_EVM_TESTNET"= "DeFiChain EVM Testnet",
  "DFK_CHAIN"= "DFK Chain",
  "DOGECHAIN"= "Dogechain",
  "EDGEWARE_EDGEEVM_MAINNET"= "Edgeware EdgeEVM Mainnet",
  "EKTA"= "Ekta",
  "EKTA_TESTNET"= "Ekta Testnet",
  "EOS_EVM"= "EOS EVM",
  "EOS_EVM_TESTNET"= "EOS EVM Testnet",
  "ETHEREUM"= "Ethereum",
  "ETHEREUM_CLASSIC"= "Ethereum Classic",
  "EVMOS"= "Evmos",
  "EVMOS_TESTNET"= "Evmos Testnet",
  "FANTOM"= "Fantom",
  "FANTOM_SONIC_OPEN_TESTNET"= "Fantom Sonic Open Testnet",
  "FANTOM_TESTNET"= "Fantom Testnet",
  "FIBO_CHAIN"= "Fibo Chain",
  "FILECOIN_CALIBRATION"= "Filecoin Calibration",
  "FILECOIN_HYPERSPACE"= "Filecoin Hyperspace",
  "FILECOIN_MAINNET"= "Filecoin Mainnet",
  "FLARE_MAINNET"= "Flare Mainnet",
  "FOUNDRY"= "Foundry",
  "FUSE"= "Fuse",
  "FUSE_SPARKNET"= "Fuse Sparknet",
  "GNOSIS"= "Gnosis",
  "GNOSIS_CHIADO"= "Gnosis Chiado",
  "GOERLI"= "Goerli",
  "HAQQ_MAINNET"= "HAQQ Mainnet",
  "HAQQ_TESTEDGE_2"= "HAQQ Testedge 2",
  "HARDHAT"= "Hardhat",
  "HARMONY_ONE"= "Harmony One",
  "HEDERA_MAINNET"= "Hedera Mainnet",
  "HEDERA_PREVIEWNET"= "Hedera Previewnet",
  "HEDERA_TESTNET"= "Hedera Testnet",
  "HOLESKY"= "Holesky",
  "HORIZEN_GOBI_TESTNET"= "Horizen Gobi Testnet",
  "IOTEX"= "IoTeX",
  "IOTEX_TESTNET"= "IoTeX Testnet",
  "JIBCHAIN_L1"= "JIBCHAIN L1",
  "KARURA"= "Karura",
  "KAVA_EVM"= "Kava EVM",
  "KAVA_EVM_TESTNET"= "Kava EVM Testnet",
  "KCC_MAINNET"= "KCC Mainnet",
  "KLAYTN"= "Klaytn",
  "KLAYTN_BAOBAB_TESTNET"= "Klaytn Baobab Testnet",
  "KROMA"= "Kroma",
  "KROMA_SEPOLIA"= "Kroma Sepolia",
  "LIGHTLINK_PEGASUS_TESTNET"= "LightLink Pegasus Testnet",
  "LIGHTLINK_PHOENIX"= "LightLink Phoenix",
  "LINEA_GOERLI_TESTNET"= "Linea Goerli Testnet",
  "LINEA_MAINNET"= "Linea Mainnet",
  "LOCALHOST"= "Localhost",
  "LUKSO"= "LUKSO",
  "MANDALA_TC9"= "Mandala TC9",
  "MANTA_PACIFIC_MAINNET"= "Manta Pacific Mainnet",
  "MANTA_PACIFIC_TESTNET"= "Manta Pacific Testnet",
  "MANTLE"= "Mantle",
  "MANTLE_TESTNET"= "Mantle Testnet",
  "METACHAIN_MAINNET"= "MetaChain Mainnet",
  "METER"= "Meter",
  "METER_TESTNET"= "Meter Testnet",
  "METIS"= "Metis",
  "METIS_GOERLI"= "Metis Goerli",
  "MEVERSE_CHAIN_MAINNET"= "MEVerse Chain Mainnet",
  "MEVERSE_CHAIN_TESTNET"= "MEVerse Chain Testnet",
  "MODE_TESTNET"= "Mode Testnet",
  "MOONBASE_ALPHA"= "Moonbase Alpha",
  "MOONBEAM"= "Moonbeam",
  "MOONBEAM_DEVELOPMENT_NODE"= "Moonbeam Development Node",
  "MOONRIVER"= "Moonriver",
  "NEON_EVM_DEVNET"= "Neon EVM DevNet",
  "NEON_EVM_MAINNET"= "Neon EVM MainNet",
  "NEXI"= "Nexi",
  "NEXILIX_SMART_CHAIN"= "Nexilix Smart Chain",
  "OASIS_SAPPHIRE"= "Oasis Sapphire",
  "OASIS_SAPPHIRE_TESTNET"= "Oasis Sapphire Testnet",
  "OASIS_TESTNET"= "Oasis Testnet",
  "OASYS"= "Oasys",
  "OKC"= "OKC",
  "OORT_MAINNETDEV"= "OORT MainnetDev",
  "OPBNB"= "opBNB",
  "OPBNB_TESTNET"= "opBNB Testnet",
  "OPTIMISM_GOERLI"= "Optimism Goerli",
  "OP_MAINNET"= "Optimism",
  "OP_SEPOLIA"= "Optimism Sepolia",
  "PALM"= "Palm",
  "PALM_TESTNET"= "Palm Testnet",
  "PGN"= "PGN",
  "PGN_"= "PGN ",
  "PLINGA"= "Plinga",
  "POLYGON"= "Polygon",
  "POLYGON_AMOY"= "Polygon Amoy",
  "POLYGON_MUMBAI"= "Polygon Mumbai",
  "POLYGON_ZKEVM"= "Polygon zkEVM",
  "POLYGON_ZKEVM_TESTNET"= "Polygon zkEVM Testnet",
  "PULSECHAIN"= "PulseChain",
  "PULSECHAIN_V4"= "PulseChain V4",
  "Q_MAINNET"= "Q Mainnet",
  "Q_TESTNET"= "Q Testnet",
  "ROLLUX_MAINNET"= "Rollux Mainnet",
  "ROLLUX_TESTNET"= "Rollux Testnet",
  "RONIN"= "Ronin",
  "ROOTSTOCK_MAINNET"= "Rootstock Mainnet",
  "SAIGON_TESTNET"= "Saigon Testnet",
  "SCROLL"= "Scroll",
  "SCROLL_SEPOLIA"= "Scroll Sepolia",
  "SCROLL_TESTNET"= "Scroll Testnet",
  "SEPOLIA"= "Ethereum Sepolia",
  "SHARDEUM_SPHINX"= "Shardeum Sphinx",
  "SHIBARIUM"= "Shibarium",
  "SHIMMER"= "Shimmer",
  "SHIMMER_TESTNET"= "Shimmer Testnet",
  "SKALE_|_BLOCK_BRAWLERS"= "SKALE | Block Brawlers",
  "SKALE_|_CALYPSO_NFT_HUB"= "SKALE | Calypso NFT Hub",
  "SKALE_|_CALYPSO_NFT_HUB_TESTNET"= "SKALE | Calypso NFT Hub Testnet",
  "SKALE_|_CHAOS_TESTNET"= "SKALE | Chaos Testnet",
  "SKALE_|_CRYPTOBLADES"= "SKALE | CryptoBlades",
  "SKALE_|_CRYPTO_COLOSSEUM"= "SKALE | Crypto Colosseum",
  "SKALE_|_EUROPA_LIQUIDITY_HUB"= "SKALE | Europa Liquidity Hub",
  "SKALE_|_EUROPA_LIQUIDITY_HUB_TESTNET"= "SKALE | Europa Liquidity Hub Testnet",
  "SKALE_|_EXORDE"= "SKALE | Exorde",
  "SKALE_|_HUMAN_PROTOCOL"= "SKALE | Human Protocol",
  "SKALE_|_NEBULA_GAMING_HUB"= "SKALE | Nebula Gaming Hub",
  "SKALE_|_NEBULA_GAMING_HUB_TESTNET"= "SKALE | Nebula Gaming Hub Testnet",
  "SKALE_|_RAZOR_NETWORK"= "SKALE | Razor Network",
  "SKALE_|_TITAN_COMMUNITY_HUB"= "SKALE | Titan Community Hub",
  "SKALE_|_TITAN_COMMUNITY_HUB_TESTNET"= "SKALE | Titan Community Hub Testnet",
  "SONGBIRD_MAINNET"= "Songbird Mainnet",
  "SYSCOIN_MAINNET"= "Syscoin Mainnet",
  "SYSCOIN_TANENBAUM_TESTNET"= "Syscoin Tanenbaum Testnet",
  "TAIKO_(ALPHA-3_TESTNET)"= "Taiko (Alpha-3 Testnet)",
  "TAIKO_JOLNIR_(ALPHA-5_TESTNET)"= "Taiko Jolnir (Alpha-5 Testnet)",
  "TAIKO_KATLA_(ALPHA-6_TESTNET)"= "Taiko Katla (Alpha-6 Testnet)",
  "TARAXA_MAINNET"= "Taraxa Mainnet",
  "TARAXA_TESTNET"= "Taraxa Testnet",
  "TELOS"= "Telos",
  "TENET"= "Tenet",
  "VECHAIN"= "Vechain",
  "WANCHAIN"= "Wanchain",
  "WANCHAIN_TESTNET"= "Wanchain Testnet",
  "WEMIX"= "WEMIX",
  "WEMIX_TESTNET"= "WEMIX Testnet",
  "X1_TESTNET"= "X1 Testnet",
  "XINFIN_NETWORK"= "XinFin Network",
  "ZETACHAIN_ATHENS_TESTNET"= "ZetaChain Athens Testnet",
  "ZHEJIANG"= "Zhejiang",
  "ZILLIQA"= "Zilliqa",
  "ZILLIQA_TESTNET"= "Zilliqa Testnet",
  "ZKFAIR_MAINNET"= "ZKFair Mainnet",
  "ZKFAIR_TESTNET"= "ZKFair Testnet",
  "ZKSYNC_ERA"= "zkSync Era",
  "ZKSYNC_ERA_TESTNET"= "zkSync Era Testnet",
  "ZKSYNC_SEPOLIA_TESTNET"= "zkSync Sepolia Testnet",
  "ZORA"= "Zora",
  "ZORA_GOERLI_TESTNET"= "Zora Goerli Testnet",
  "ZORA_SEPOLIA"= "Zora Sepolia",
}

export enum OperationStatusEnum {
  Pending = 'pending',
  Completed = 'completed',
  Failed = 'failed',
  Received = 'received',
  Success = 'success',
  Failure = 'failure',
  Dropped = 'dropped',
  Replaced = 'replaced',
  Stuck = 'stuck',
  Confirmed = 'confirmed'
}
export enum TransactionType {
  USER_TO_TMC = 'user_to_tmc',
  TMC_TO_USER = 'tmc_to_user',
  RELAYER_TO_TMC = 'relayer_to_tmc',
  RELAYER_TO_CODEX = 'relayer_to_codex',
  RELAYER_TO_CIRCLE = 'relayer_to_circle',
}

export enum ACTION_TYPE {
  D = 'deposit',
  W = "withdraw",
  T = "transfer"
}